### ISSUE TITLE
Configuration after eject

### ISSUE THREAD

**Issue by taviroquai** [ant-design/create-react-app-antd#10]
Hi,

After "eject" I'm not able to run with: $ npm run start

This is the error:

> 
> create-react-app-antd@0.1.0 start /home/mafonso/projects/create-react-app-antd-master
> react-app-rewired start
> 
> module.js:491
>     throw err;
>     ^
> 
> Error: Cannot find module 'react-scripts/config/paths'

How to make it work after eject?

Thanks

**Comment by cc616** [comment]
you need npm install react-scripts
then is ok

**Comment by ackvf** [comment]
I am using `react-scripts-ts` and I also get this error.

`
    "start": "react-app-rewired start --scripts-version react-scripts-ts",
`
