### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by BangyuanX** [ant-design/create-react-app-antd#130]
./node_modules/antd/es/button/style/index.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-7-3!./node_modules/antd/es/button/style/index.less)
ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'source'. These properties are valid:
   object { lessOptions?, prependData?, appendData?, sourceMap? }

**Comment by olopk** [comment]
I have the same problem, download the repo by git clone, then installed the node modules with npm install, and finally it fails to compile after npm start.

**Comment by EHENJOOM** [comment]
Me too. when "style" in "fixBabelImports" is "true",it would give the message "failed to compile".

**Comment by jahlomp** [comment]
Check this video out https://www.youtube.com/watch?v=FizDLRlE6NE

**Comment by olopk** [comment]
> Check this video out https://www.youtube.com/watch?v=FizDLRlE6NE

Thats awesome, thank You.

**Comment by BangyuanX** [comment]
> Check this video out https://www.youtube.com/watch?v=FizDLRlE6NE

It works now. Thank you.
