### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by csulit** [ant-design/create-react-app-antd#155]
./src/App.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-8-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-8-3!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-8-4!./src/App.less)
ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'javascriptEnabled'. These properties are valid:
   object { lessOptions?, prependData?, appendData?, sourceMap?, implementation? }

**Comment by hehex9** [comment]
今天也遇到了，不过看来已经更新了，[看这里](https://github.com/ant-design/create-react-app-antd/blob/master/craco.config.js#L9) @csulit

**Comment by afc163** [comment]
https://github.com/ant-design/create-react-app-antd/commit/5d0db6e62eba27163b59edf45a23732e6318eed6

**Comment by csulit** [comment]
Issue was resolved downgrade less-loader to version 5.0.0
