### ISSUE TITLE
yarn start 之后出现injectBabelPlugin is not a function

### ISSUE THREAD

**Issue by PilgrimS** [ant-design/create-react-app-antd#22]
yarn run v1.12.3
$ react-app-rewired start
injectBabelPlugin is not a function
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by guanpengchn** [comment]
react-app-rewired不维护了，react-scripts升级后又删除了一些东西，不建议使用antd官网的高级配置，现在有坑

**Comment by afc163** [comment]
Close in favor of https://github.com/ant-design/ant-design/pull/14385
