### ISSUE TITLE
Importing AntD CSS

### ISSUE THREAD

**Issue by loganpowell** [ant-design/create-react-app-antd#5]
First, thank you so much for starting to support the UNIX ethos by making AntD integrate with create-react-app for those who might be intimidated by the full DVa experience. I'm very much looking forward to using this incredible library! 

Question: Are you now looking into separating antd from dva for non saga users and users of react-router v4?

(edit: sorry about the initial css question. I made a stupid syntax error)

**Comment by afc163** [comment]
It is a dva-related question, you could ask it in https://github.com/dvajs/dva/issues
