### ISSUE TITLE
Is it better to put customize-cra react-app-rewired at devdependency ?

### ISSUE THREAD

**Issue by leaez** [ant-design/create-react-app-antd#66]
Is it better to use yarn add customize-cra react-app-rewired --dev,

**Comment by ostrebler** [comment]
Yes.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/19125#issuecomment-539799411

**Comment by afc163** [comment]
https://github.com/facebook/create-react-app/issues/6180#issuecomment-453640473
https://github.com/facebook/create-react-app/pull/7435#issuecomment-515546113
