### ISSUE TITLE
请问，此项目是不是antd使用create-react-app的官方脚手架？

### ISSUE THREAD

**Issue by Witee** [ant-design/create-react-app-antd#7]
antd 使用 create-react-app 的文档是 `https://ant.design/docs/react/use-with-create-react-app-cn`，此项目是不是按照此文档进行的配置呢？

如果我的项目只使用antd的组件，是不是可以直接使用此脚手架而不需要从 create-react-app 自己配置？

**Comment by afc163** [comment]
建议还是从 create-react-app 开始，因为 create-react-app 一直在更新。

**Comment by Witee** [comment]
好的，那我从create-react-app开始，并按照 `https://ant.design/docs/react/use-with-create-react-app-cn` 配置。

感谢
