### ISSUE TITLE
seems like babel-plugin-import is not working 

### ISSUE THREAD

**Issue by ravirambles** [ant-design/create-react-app-antd#8]
I have cloned this repo and ran "yarn start" 

![inkedcode_2017-08-30_19-19-08_li](https://user-images.githubusercontent.com/809061/29900546-46be53c8-8db8-11e7-9f46-eba5ee06f540.jpg)

getting the bable-loader not found error.

and the antd is displaying an error in the console about the whole library being used 
and styles are not getting applied. 

I just included the main antd less file for now to continue working 
but seems like the react-app-rewired is not able to find the 'babel-plugin-import' 

let me know if am missing something

**Comment by ravirambles** [comment]
after some digging around I found the issue and it is an issue with the react-app-rewired and only effecting windows systems.  there is already a pull request for it 

https://github.com/timarney/react-app-rewired/pull/81

this can closed

**Comment by afc163** [comment]
Keep it open until react-app-rewired release a new version.

**Comment by Wang1995** [comment]
you can try  to run 'npm eject'

**Comment by ravirambles** [comment]
this has already been fixed in the latest react-app-rewired please update the package to the latest. I am not familiar with the process of creating a pull request (going to take the time to learn it).
