### ISSUE TITLE
babel-loader not found

### ISSUE THREAD

**Issue by sonovice** [ant-design/create-react-app-antd#9]
I just download the repo and executed `yarn install` and `yarn start`. Unfortunately the Button on the web page is not styled with antd.

There is no error, but in the console it says "babel-loader not found". Adding it to the dependencies did not work.

Any ideas on how to fix that?

**Comment by afc163** [comment]
https://github.com/ant-design/create-react-app-antd/issues/8

**Comment by sonovice** [comment]
@afc163 Okay, thanks. I did not look through closed issues, my bad. Maybe you should leave this one open so other people see it as well as long as the error in rewire persists.
